adminCommande:
    path:   /
    defaults: { _controller: ShopBundle:CommandesAdmin:commandes }

adminShowFacture:
    path:   /facture/{id}
    defaults: { _controller: ShopBundle:CommandesAdmin:showFacture }