supprimer:
    path:   /supprimer/{id}
    defaults: { _controller: ShopBundle:Panier:supprimer }

ajouter:
    path:     /ajouter/{id}
    defaults: { _controller: ShopBundle:Panier:ajouter }

panier:
    path:     /
    defaults: { _controller: ShopBundle:Panier:panier }

livraison:
    path:     /livraison
    defaults: { _controller: ShopBundle:Panier:livraison }

validation:
    path:     /validation
    defaults: { _controller: ShopBundle:Panier:validation }

livraisonAdresseSuppression:
    path:     /livraison/adresse/supression/{id}
    defaults: { _controller: ShopBundle:Panier:adresseSuppression }