adminProduits_index:
    path:     /
    defaults: { _controller: "ShopBundle:ProduitsAdmin:index" }
    methods:  GET

adminProduits_show:
    path:     /{id}/show
    defaults: { _controller: "ShopBundle:ProduitsAdmin:show" }
    methods:  GET

adminProduits_new:
    path:     /new
    defaults: { _controller: "ShopBundle:ProduitsAdmin:new" }
    methods:  [GET, POST]

adminProduits_edit:
    path:     /{id}/edit
    defaults: { _controller: "ShopBundle:ProduitsAdmin:edit" }
    methods:  [GET, POST]

adminProduits_delete:
    path:     /{id}/delete
    defaults: { _controller: "ShopBundle:ProduitsAdmin:delete" }
    methods:  DELETE
