routingPanier:
    resource: "@ShopBundle/Resources/config/routing/routingPanier.yml"
    prefix: /panier

routingProduits:
    resource: "@ShopBundle/Resources/config/routing/routingProduits.yml"
    prefix: /