factures:
    pattern: /profile/factures
    defaults: { _controller: UtilisateursBundle:Utilisateurs:factures }

facturesPDF:
    pattern: /profile/factures/pdf/{id}
    defaults: { _controller: UtilisateursBundle:Utilisateurs:facturesPDF }

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"